DROP TABLE IF EXISTS orders;
DROP TABLE IF EXISTS products;
DROP TABLE IF EXISTS artists;
DROP TABLE IF EXISTS labels;
DROP TABLE IF EXISTS users;

CREATE TABLE users (
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rut VARCHAR(255) UNIQUE NOT NULL,
    age INTEGER,
    first_name VARCHAR(255) NOT NULL,
    last_name VARCHAR(255) NOT NULL,
    phone VARCHAR(255),
    email VARCHAR(255) UNIQUE NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    created_at TIMESTAMP,
    role VARCHAR(50),
    is_active BOOLEAN
);

CREATE TABLE artists (
    artist_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    artist_name VARCHAR(255) NOT NULL,
    country VARCHAR(255),
    founded_year INTEGER,
    genre VARCHAR(255),
    is_active BOOLEAN
);

CREATE TABLE labels (
    label_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    label_name VARCHAR(255) NOT NULL,
    country VARCHAR(255),
    founded_year INTEGER,
    website VARCHAR(255),
    contact_email VARCHAR(255)
);

CREATE TABLE products (
    product_id VARCHAR(255) PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    artist_id BIGINT NOT NULL,
    label_id BIGINT NOT NULL,
    format_name VARCHAR(255) NOT NULL,
    format_type VARCHAR(255) NOT NULL,
    image_url VARCHAR(255) NOT NULL,
    release_year INTEGER,
    description VARCHAR(255),
    price INTEGER NOT NULL,
    stock_quantity INTEGER,
    avg_rating DOUBLE,
    rating_count INTEGER,
    is_available BOOLEAN,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    CONSTRAINT fk_products_artist FOREIGN KEY (artist_id) REFERENCES artists(artist_id),
    CONSTRAINT fk_products_label FOREIGN KEY (label_id) REFERENCES labels(label_id)
);

CREATE TABLE orders (
    order_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id BIGINT NOT NULL,
    product_id VARCHAR(255) NOT NULL,
    artist_id BIGINT,
    label_id BIGINT,
    responsible_user_id BIGINT,
    quantity INTEGER NOT NULL,
    total_price INTEGER NOT NULL,
    status VARCHAR(50) NOT NULL,
    order_date TIMESTAMP,
    updated_at TIMESTAMP,
    CONSTRAINT fk_orders_customer FOREIGN KEY (customer_id) REFERENCES users(user_id),
    CONSTRAINT fk_orders_product FOREIGN KEY (product_id) REFERENCES products(product_id),
    CONSTRAINT fk_orders_artist FOREIGN KEY (artist_id) REFERENCES artists(artist_id),
    CONSTRAINT fk_orders_label FOREIGN KEY (label_id) REFERENCES labels(label_id),
    CONSTRAINT fk_orders_responsible FOREIGN KEY (responsible_user_id) REFERENCES users(user_id)
);
